add_executable("AssetCreator"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/AlResource.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/AudioResource.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/Export.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/InputSoundFile.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/Listener.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/Music.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/OutputSoundFile.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/PlaybackDevice.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/Sound.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundBuffer.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundBufferRecorder.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundChannel.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundFileFactory.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundFileReader.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundFileWriter.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundRecorder.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundSource.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Audio/SoundStream.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Config.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/GpuPreference.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/BlendMode.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/CircleShape.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Color.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/ConvexShape.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/CoordinateType.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Drawable.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Export.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Font.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Glsl.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Glyph.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Image.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/PrimitiveType.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Rect.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/RectangleShape.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/RenderStates.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/RenderTarget.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/RenderTexture.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/RenderWindow.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Shader.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Shape.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Sprite.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/StencilMode.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Text.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Texture.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Transform.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Transformable.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/Vertex.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/VertexArray.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/VertexBuffer.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Graphics/View.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Main.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/Export.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/Ftp.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/Http.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/IpAddress.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/Packet.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/Socket.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/SocketHandle.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/SocketSelector.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/TcpListener.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/TcpSocket.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Network/UdpSocket.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/OpenGL.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Angle.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Clock.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Err.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Exception.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Export.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/FileInputStream.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/InputStream.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Lock.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/MemoryInputStream.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Mutex.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/NativeActivity.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/NonCopyable.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Sleep.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/String.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/SuspendAwareClock.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Thread.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/ThreadLocal.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/ThreadLocalPtr.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Time.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Utf.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Vector2.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/System/Vector3.hpp"
          "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Clipboard.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Context.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/ContextSettings.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Cursor.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Event.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Export.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/GlResource.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Joystick.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Keyboard.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Mouse.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Sensor.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Touch.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/VideoMode.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Vulkan.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/Window.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/WindowBase.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/WindowEnums.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/WindowHandle.hpp"
            "AssetCreator/3rdParty/SFML-3.0.0/include/SFML/Window/WindowStyle.hpp"
        "AssetCreator/3rdParty/SoLoud/include/soloud.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_audiosource.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_bassboostfilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_biquadresonantfilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_bus.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_c.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_dcremovalfilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_echofilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_error.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_fader.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_fft.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_fftfilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_file.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_file_hack_off.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_file_hack_on.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_filter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_flangerfilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_freeverbfilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_internal.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_lofifilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_misc.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_monotone.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_noise.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_openmpt.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_queue.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_robotizefilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_sfxr.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_speech.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_tedsid.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_thread.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_vic.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_vizsn.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_wav.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_waveshaperfilter.h"
        "AssetCreator/3rdParty/SoLoud/include/soloud_wavstream.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/monotone/soloud_monotone.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/noise/soloud_noise.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/openmpt/soloud_openmpt.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/openmpt/soloud_openmpt_dll.c"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/sfxr/soloud_sfxr.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/darray.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/darray.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/klatt.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/klatt.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/resonator.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/resonator.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/soloud_speech.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/tts.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/speech/tts.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/tedsid/sid.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/tedsid/sid.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/tedsid/soloud_tedsid.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/tedsid/ted.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/tedsid/ted.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/vic/soloud_vic.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/vizsn/soloud_vizsn.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/dr_flac.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/dr_impl.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/dr_mp3.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/dr_wav.h"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/soloud_wav.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/soloud_wavstream.cpp"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/stb_vorbis.c"
            "AssetCreator/3rdParty/SoLoud/src/audiosource/wav/stb_vorbis.h"
            "AssetCreator/3rdParty/SoLoud/src/backend/miniaudio/miniaudio.h"
            "AssetCreator/3rdParty/SoLoud/src/backend/miniaudio/soloud_miniaudio.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_audiosource.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_bus.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_3d.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_basicops.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_faderops.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_filterops.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_getters.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_setters.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_voicegroup.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_core_voiceops.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_fader.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_fft.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_fft_lut.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_file.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_filter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_misc.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_queue.cpp"
          "AssetCreator/3rdParty/SoLoud/src/core/soloud_thread.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_bassboostfilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_biquadresonantfilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_dcremovalfilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_echofilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_fftfilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_flangerfilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_freeverbfilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_lofifilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_robotizefilter.cpp"
          "AssetCreator/3rdParty/SoLoud/src/filter/soloud_waveshaperfilter.cpp"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/anchor.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/binary.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/contrib/anchordict.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/contrib/graphbuilder.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/depthguard.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/dll.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/emitfromevents.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/emitter.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/emitterdef.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/emittermanip.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/emitterstyle.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/eventhandler.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/exceptions.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/fptostring.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/mark.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/convert.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/impl.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/iterator.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/iterator_fwd.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/memory.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/node.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/node_data.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/node_iterator.h"
              "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/detail/node_ref.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/emit.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/impl.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/iterator.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/node.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/parse.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/ptr.h"
            "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/node/type.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/noexcept.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/null.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/ostream_wrapper.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/parser.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/stlemitter.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/traits.h"
          "AssetCreator/3rdParty/yaml-cpp/include/yaml-cpp/yaml.h"
    "AssetCreator/src/Application.cpp"
    "AssetCreator/src/Application.h"
    "AssetCreator/src/Logger.h"
      "AssetCreator/src/imgui/imconfig-SFML.h"
      "AssetCreator/src/imgui/imconfig.h"
      "AssetCreator/src/imgui/imfilebrowser.h"
      "AssetCreator/src/imgui/imgui-SFML.cpp"
      "AssetCreator/src/imgui/imgui-SFML.h"
      "AssetCreator/src/imgui/imgui-SFML_export.h"
      "AssetCreator/src/imgui/imgui.cpp"
      "AssetCreator/src/imgui/imgui.h"
      "AssetCreator/src/imgui/imgui_demo.cpp"
      "AssetCreator/src/imgui/imgui_draw.cpp"
      "AssetCreator/src/imgui/imgui_internal.h"
      "AssetCreator/src/imgui/imgui_tables.cpp"
      "AssetCreator/src/imgui/imgui_widgets.cpp"
      "AssetCreator/src/imgui/imstb_rectpack.h"
      "AssetCreator/src/imgui/imstb_textedit.h"
      "AssetCreator/src/imgui/imstb_truetype.h"
      "AssetCreator/src/main.cpp"
      "AssetCreator/src/AssetInfo/SpriteAsset.h"
      "AssetCreator/src/Utils/SpriteType.h"
        "AssetCreator/src/UIStuff/ImGuiArea.h"
        "AssetCreator/src/UIStuff/LeftArea.cpp"
        "AssetCreator/src/UIStuff/LeftArea.h"
        "AssetCreator/src/UIStuff/RightArea.cpp"
        "AssetCreator/src/UIStuff/RightArea.h"
        "AssetCreator/src/Utils/SpriteType.cpp"
        "AssetCreator/src/AssetInfo/SpriteAsset.cpp"
        "AssetCreator/src/AssetInfo/AudioAsset.h"
        "AssetCreator/src/AssetInfo/FontAsset.h"
        "AssetCreator/src/AssetInfo/BaseAsset.h"
        "AssetCreator/src/AssetInfo/Frame.h"
)
if(CMAKE_BUILD_TYPE STREQUAL Debug)
  set_target_properties("AssetCreator" PROPERTIES
    OUTPUT_NAME "AssetCreator"
    ARCHIVE_OUTPUT_DIRECTORY "/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Debug"
    LIBRARY_OUTPUT_DIRECTORY "/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Debug"
    RUNTIME_OUTPUT_DIRECTORY "/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Debug"
  )
endif()
target_include_directories("AssetCreator" PRIVATE
  $<$<CONFIG:Debug>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/AssetCreator/3rdParty/SFML-3.0.0/include>
  $<$<CONFIG:Debug>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/AssetCreator/3rdParty/SoLoud/include>
  $<$<CONFIG:Debug>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/AssetCreator/3rdParty/yaml-cpp/include>
)
target_compile_definitions("AssetCreator" PRIVATE
  $<$<CONFIG:Debug>:ABYSS_PLATFORM_LINUX>
  $<$<CONFIG:Debug>:SFML_STATIC>
  $<$<CONFIG:Debug>:ABYSS_DEBUG>
  $<$<CONFIG:Debug>:WITH_MINIAUDIO>
)
target_link_directories("AssetCreator" PRIVATE
  $<$<CONFIG:Debug>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Debug>
)
target_link_libraries("AssetCreator"
  $<$<CONFIG:Debug>:sfml-graphics-s-d>
  $<$<CONFIG:Debug>:sfml-audio-s-d>
  $<$<CONFIG:Debug>:sfml-network-s-d>
  $<$<CONFIG:Debug>:sfml-window-s-d>
  $<$<CONFIG:Debug>:sfml-system-s-d>
  $<$<CONFIG:Debug>:yaml-cpp>
  $<$<CONFIG:Debug>:freetype>
  $<$<CONFIG:Debug>:X11>
  $<$<CONFIG:Debug>:Xi>
  $<$<CONFIG:Debug>:Xxf86vm>
  $<$<CONFIG:Debug>:Xrandr>
  $<$<CONFIG:Debug>:Xcursor>
  $<$<CONFIG:Debug>:udev>
  $<$<CONFIG:Debug>:GL>
  $<$<CONFIG:Debug>:openal>
  $<$<CONFIG:Debug>:FLAC>
  $<$<CONFIG:Debug>:ogg>
  $<$<CONFIG:Debug>:vorbis>
  $<$<CONFIG:Debug>:pthread>
)
if(CMAKE_BUILD_TYPE STREQUAL Debug)
  set_target_properties("AssetCreator" PROPERTIES COMPILE_FLAGS "-fPIC ")
endif()
target_compile_options("AssetCreator" PRIVATE
  $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-m64>
  $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-O0>
  $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g>
  $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-m64>
  $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-O0>
  $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g>
)
if(CMAKE_BUILD_TYPE STREQUAL Release)
  set_target_properties("AssetCreator" PROPERTIES
    OUTPUT_NAME "AssetCreator"
    ARCHIVE_OUTPUT_DIRECTORY "/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Release"
    LIBRARY_OUTPUT_DIRECTORY "/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Release"
    RUNTIME_OUTPUT_DIRECTORY "/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Release"
  )
endif()
target_include_directories("AssetCreator" PRIVATE
  $<$<CONFIG:Release>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/AssetCreator/3rdParty/SFML-3.0.0/include>
  $<$<CONFIG:Release>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/AssetCreator/3rdParty/SoLoud/include>
  $<$<CONFIG:Release>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/AssetCreator/3rdParty/yaml-cpp/include>
)
target_compile_definitions("AssetCreator" PRIVATE
  $<$<CONFIG:Release>:ABYSS_PLATFORM_LINUX>
  $<$<CONFIG:Release>:SFML_STATIC>
  $<$<CONFIG:Release>:ABYSS_RELEASE>
  $<$<CONFIG:Release>:WITH_MINIAUDIO>
)
target_link_directories("AssetCreator" PRIVATE
  $<$<CONFIG:Release>:/home/lekrieg/Documents/Projects/3D2Y/Tools/AssetCreator/Lib/linuxx86_64Release>
)
target_link_libraries("AssetCreator"
  $<$<CONFIG:Release>:sfml-graphics-s>
  $<$<CONFIG:Release>:sfml-audio-s>
  $<$<CONFIG:Release>:sfml-network-s>
  $<$<CONFIG:Release>:sfml-system-s>
  $<$<CONFIG:Release>:sfml-window-s>
  $<$<CONFIG:Release>:yaml-cpp>
  $<$<CONFIG:Release>:freetype>
  $<$<CONFIG:Release>:X11>
  $<$<CONFIG:Release>:Xi>
  $<$<CONFIG:Release>:Xxf86vm>
  $<$<CONFIG:Release>:Xrandr>
  $<$<CONFIG:Release>:Xcursor>
  $<$<CONFIG:Release>:udev>
  $<$<CONFIG:Release>:GL>
  $<$<CONFIG:Release>:openal>
  $<$<CONFIG:Release>:FLAC>
  $<$<CONFIG:Release>:ogg>
  $<$<CONFIG:Release>:vorbis>
  $<$<CONFIG:Release>:pthread>
)
target_compile_options("AssetCreator" PRIVATE
  $<$<AND:$<CONFIG:Release>,$<COMPILE_LANGUAGE:C>>:-m64>
  $<$<AND:$<CONFIG:Release>,$<COMPILE_LANGUAGE:C>>:-O2>
  $<$<AND:$<CONFIG:Release>,$<COMPILE_LANGUAGE:CXX>>:-m64>
  $<$<AND:$<CONFIG:Release>,$<COMPILE_LANGUAGE:CXX>>:-O2>
)