#ifndef ABYSS_ENUMS_H
#define ABYSS_ENUMS_H

enum class ABYSS_FILE_TYPE
{
	ABYSS_TEXT_FILE = 1,
	ABYSS_BINARY_FILE
};

enum class ABYSS_ENDIAN_TYPE
{
	ABYSS_ENDIAN_UNKNOWN = 0,
	ABYSS_ENDIAN_LITTLE,
	ABYSS_ENDIAN_BIG,
	ABYSS_ENDIAN_MIDDLE
};

enum class ABYSS_COORDINATE_TYPE
{
	ABYSS_LEFT_HANDED = 1,
	ABYSS_RIGHT_HANDED
};

enum class ABYSS_PLANE_STATUS
{
	ABYSS_PLANE_FRONT = 1,
	ABYSS_PLANE_BACK,
	ABYSS_PLANE_ON_PLANE,
	ABYSS_PLANE_CLIPPED,
	ABYSS_PLANE_CULLED,
	ABYSS_PLANE_VISIBLE
};

// General defines, etc.
enum class ABYSS_RESULT
{
	ABYSS_FAIL = 0,
	ABYSS_SUCCESS,
	ABYSS_VERTEX_SHADER_FAIL,
	ABYSS_FRAGMENT_SHADER_FAIL,
	ABYSS_SHADER_FAIL,
	ABYSS_PARAMETERS_FAIL,
	ABYSS_DEVICE_FAIL
};

// Networking defines, etc.
enum class ABYSS_NETWORK_MESSAGE_TYPE
{
	ABYSS_MESSAGE_SERVER_DISCONNECT = 0,
	ABYSS_MESSAGE_CLIENT_DISCONNECT,
	ABYSS_MESSAGE_FORCE_DISCONNECT,
	ABYSS_MESSAGE_CONNECT_ACCEPTED,
	ABYSS_MESSAGE_SEND_ERROR,
	ABYSS_MESSAGE_RESPOND_REQUIRE,
	ABYSS_MESSAGE_RESPOND_OK
};

enum class ABYSS_NETWORK_TYPE
{
	ABYSS_NETWORK_NULL = 0,
	ABYSS_NETWORK_SERVER,
	ABYSS_NETWORK_CLIENT
};

enum class ABYSSNETWORKRESULT
{
	ABYSS_NO_DATA = 0,
	ABYSS_DATA_FAIL,
	ABYSS_PARTIAL_DATA,
	ABYSS_DATA_SUCCESS
};

// Defines, enums, etc dealing with RENDERING.
enum class ABYSS_RENDER_STATE
{
	ABYSS_DEPTH_TESTING = 1,
	ABYSS_SMOOTH_SHADING,
	ABYSS_TEXTURE_2D,
	ABYSS_TEXTURE_CUBE,
	ABYSS_ALPHA_TESTING,
	ABYSS_BACK_CCW_CULLING,
	ABYSS_BACK_CW_CULLING,
	ABYSS_FRONT_CCW_CULLING,
	ABYSS_FRONT_CW_CULLING,
	ABYSS_TOTAL_RENDER_STATES
};

enum class ABYSS_ALPHA_STATE
{
	ABYSS_ALPHA_LESS = 1,
	ABYSS_ALPHA_GREATER
};

enum class ABYSS_FILTER_TYPE
{
	ABYSS_NO_FILTER = 0,
	ABYSS_MIN_POINT_FILTER,
	ABYSS_MAG_POINT_FILTER,
	ABYSS_MIP_POINT_FILTER,
	ABYSS_MIN_LINEAR_FILTER,
	ABYSS_MAG_LINEAR_FILTER,
	ABYSS_MIP_LINEAR_FILTER,
	ABYSS_USE_ANSIO_FILTER,
	ABYSS_S_REPEAT_FILTER,
	ABYSS_T_REPEAT_FILTER,
	ABYSS_R_REPEAT_FILTER,
	ABYSS_S_CLAMP_FILTER,
	ABYSS_T_CLAMP_FILTER,
	ABYSS_R_CLAMP_FILTER,
	ABYSS_S_EDGE_CLAMP_FILTER,
	ABYSS_T_EDGE_CLAMP_FILTER,
	ABYSS_R_EDGE_CLAMP_FILTER
};

enum class ABYSS_TEXTURE_TYPE
{
	ABYSS_TEX2D_TYPE = 1,
	ABYSS_CUBE_TYPE
};

enum class ABYSS_TEXTURE_FORMAT
{
	ABYSS_TEX_UNSIGNED_BYTE = 1,
	ABYSS_TEX_FLOAT
};

enum class ABYSS_MATRIX_TYPE
{
	ABYSS_PROJECTION_MATRIX = 1,
	ABYSS_MODELVIEW_MATRIX,
	ABYSS_TEXTURE_MATRIX,
	ABYSS_MVP_MATRIX
};

enum class ABYSS_MATRIX_FORMAT
{
	ABYSS_IDENTITY_MATRIX = 1,
	ABYSS_TRANSPOSE_MATRIX,
	ABYSS_INVERSE_MATRIX,
	ABYSS_INVERSE_TRANSPOSE_MATRIX
};

enum class ABYSS_PROJECTION_TYPE
{
	ABYSS_PROJECTION_NULL = 0,
	ABYSS_PERSPECTIVE_TYPE,
	ABYSS_ORTHO_TYPE
};

enum class ABYSS_ELEMENT_TYPE
{
	ABYSS_ELEMENT_TYPE_NULL = 0,
	ABYSS_ELEMENT_TYPE_IGNORE_2F,
	ABYSS_ELEMENT_TYPE_IGNORE_3F,
	ABYSS_ELEMENT_TYPE_VERTEX_3F,
	ABYSS_ELEMENT_TYPE_NORMAL_3F,
	ABYSS_ELEMENT_TYPE_COLOR_3F,
	ABYSS_ELEMENT_TYPE_TEX1_2F,
	ABYSS_ELEMENT_TYPE_TEX2_2F,
	ABYSS_ELEMENT_TYPE_TEX3_2F,
	ABYSS_ELEMENT_TYPE_TEX4_2F,
	ABYSS_ELEMENT_TYPE_TEX5_2F,
	ABYSS_ELEMENT_TYPE_TEX6_2F,
	ABYSS_ELEMENT_TYPE_TEX7_2F,
	ABYSS_ELEMENT_TYPE_TEX8_2F,
	ABYSS_ELEMENT_TYPE_TEX1_3F,
	ABYSS_ELEMENT_TYPE_TEX2_3F,
	ABYSS_ELEMENT_TYPE_TEX3_3F,
	ABYSS_ELEMENT_TYPE_TEX4_3F,
	ABYSS_ELEMENT_TYPE_TEX5_3F,
	ABYSS_ELEMENT_TYPE_TEX6_3F,
	ABYSS_ELEMENT_TYPE_TEX7_3F,
	ABYSS_ELEMENT_TYPE_TEX8_3F
};

enum class ABYSS_PRIMITIVE_TYPE
{
	ABYSS_PRIMITIVE_NULL = 0,
	ABYSS_PRIMITIVE_POINT_LIST,
	ABYSS_PRIMITIVE_TRI_LIST,
	ABYSS_PRIMITIVE_TRI_STRIP,
	ABYSS_PRIMITIVE_LINE_LIST,
	ABYSS_PRIMITIVE_LINE_STRIP
};

enum class ABYSS_SHADER_TYPE
{
	ABYSS_VERTEX_SHADER,
	ABYSS_FRAGMENT_SHADER
};

enum class ABYSS_OCTREE_NODE_ID
{
	TOP_FRONT_LEFT = 0,
	TOP_FRONT_RIGHT,
	TOP_BACK_LEFT,
	TOP_BACK_RIGHT,
	BOTTOM_FRONT_LEFT,
	BOTTOM_FRONT_RIGHT,
	BOTTOM_BACK_LEFT,
	BOTTOM_BACK_RIGHT
};

enum class ABYSS_INPUT_BUTTON
{
	ABYSS_BUTTON_SPACE = 32,
	ABYSS_BUTTON_APOSTROPHE = 39,
	ABYSS_BUTTON_COMMA = 44,  /* , */
	ABYSS_BUTTON_MINUS = 45,  /* - */
	ABYSS_BUTTON_PERIOD = 46, /* . */
	ABYSS_BUTTON_SLASH = 47,  /* / */
	ABYSS_BUTTON_0 = 48,
	ABYSS_BUTTON_1 = 49,
	ABYSS_BUTTON_2 = 50,
	ABYSS_BUTTON_3 = 51,
	ABYSS_BUTTON_4 = 52,
	ABYSS_BUTTON_5 = 53,
	ABYSS_BUTTON_6 = 54,
	ABYSS_BUTTON_7 = 55,
	ABYSS_BUTTON_8 = 56,
	ABYSS_BUTTON_9 = 57,
	ABYSS_BUTTON_SEMICOLON = 59, /* ; */
	ABYSS_BUTTON_EQUAL = 61,	 /* = */
	ABYSS_BUTTON_A = 65,
	ABYSS_BUTTON_B = 66,
	ABYSS_BUTTON_C = 67,
	ABYSS_BUTTON_D = 68,
	ABYSS_BUTTON_E = 69,
	ABYSS_BUTTON_F = 70,
	ABYSS_BUTTON_G = 71,
	ABYSS_BUTTON_H = 72,
	ABYSS_BUTTON_I = 73,
	ABYSS_BUTTON_J = 74,
	ABYSS_BUTTON_K = 75,
	ABYSS_BUTTON_L = 76,
	ABYSS_BUTTON_M = 77,
	ABYSS_BUTTON_N = 78,
	ABYSS_BUTTON_O = 79,
	ABYSS_BUTTON_P = 80,
	ABYSS_BUTTON_Q = 81,
	ABYSS_BUTTON_R = 82,
	ABYSS_BUTTON_S = 83,
	ABYSS_BUTTON_T = 84,
	ABYSS_BUTTON_U = 85,
	ABYSS_BUTTON_V = 86,
	ABYSS_BUTTON_W = 87,
	ABYSS_BUTTON_X = 88,
	ABYSS_BUTTON_Y = 89,
	ABYSS_BUTTON_Z = 90,
	ABYSS_BUTTON_LEFT_BRACKET = 91,	 /* [ */
	ABYSS_BUTTON_BACKSLASH = 92,	 /* \ */
	ABYSS_BUTTON_RIGHT_BRACKET = 93, /* ] */
	ABYSS_BUTTON_GRAVE_ACCENT = 96,	 /* ` */
	ABYSS_BUTTON_WORLD_1 = 161,		 /* non-US #1 */
	ABYSS_BUTTON_WORLD_2 = 162,		 /* non-US #2 */
	ABYSS_BUTTON_ESCAPE = 256,
	ABYSS_BUTTON_ENTER = 257,
	ABYSS_BUTTON_TAB = 258,
	ABYSS_BUTTON_BACKSPACE = 259,
	ABYSS_BUTTON_INSERT = 260,
	ABYSS_BUTTON_DELETE = 261,
	ABYSS_BUTTON_RIGHT = 262,
	ABYSS_BUTTON_LEFT = 263,
	ABYSS_BUTTON_DOWN = 264,
	ABYSS_BUTTON_UP = 265,
	ABYSS_BUTTON_PAGE_UP = 266,
	ABYSS_BUTTON_PAGE_DOWN = 267,
	ABYSS_BUTTON_HOME = 268,
	ABYSS_BUTTON_END = 269,
	ABYSS_BUTTON_CAPS_LOCK = 280,
	ABYSS_BUTTON_SCROLL_LOCK = 281,
	ABYSS_BUTTON_NUM_LOCK = 282,
	ABYSS_BUTTON_PRINT_SCREEN = 283,
	ABYSS_BUTTON_PAUSE = 284,
	ABYSS_BUTTON_F1 = 290,
	ABYSS_BUTTON_F2 = 291,
	ABYSS_BUTTON_F3 = 292,
	ABYSS_BUTTON_F4 = 293,
	ABYSS_BUTTON_F5 = 294,
	ABYSS_BUTTON_F6 = 295,
	ABYSS_BUTTON_F7 = 296,
	ABYSS_BUTTON_F8 = 297,
	ABYSS_BUTTON_F9 = 298,
	ABYSS_BUTTON_F10 = 299,
	ABYSS_BUTTON_F11 = 300,
	ABYSS_BUTTON_F12 = 301,
	ABYSS_BUTTON_F13 = 302,
	ABYSS_BUTTON_F14 = 303,
	ABYSS_BUTTON_F15 = 304,
	ABYSS_BUTTON_F16 = 305,
	ABYSS_BUTTON_F17 = 306,
	ABYSS_BUTTON_F18 = 307,
	ABYSS_BUTTON_F19 = 308,
	ABYSS_BUTTON_F20 = 309,
	ABYSS_BUTTON_F21 = 310,
	ABYSS_BUTTON_F22 = 311,
	ABYSS_BUTTON_F23 = 312,
	ABYSS_BUTTON_F24 = 313,
	ABYSS_BUTTON_F25 = 314,
	ABYSS_BUTTON_KP_0 = 320,
	ABYSS_BUTTON_KP_1 = 321,
	ABYSS_BUTTON_KP_2 = 322,
	ABYSS_BUTTON_KP_3 = 323,
	ABYSS_BUTTON_KP_4 = 324,
	ABYSS_BUTTON_KP_5 = 325,
	ABYSS_BUTTON_KP_6 = 326,
	ABYSS_BUTTON_KP_7 = 327,
	ABYSS_BUTTON_KP_8 = 328,
	ABYSS_BUTTON_KP_9 = 329,
	ABYSS_BUTTON_KP_DECIMAL = 330,
	ABYSS_BUTTON_KP_DIVIDE = 331,
	ABYSS_BUTTON_KP_MULTIPLY = 332,
	ABYSS_BUTTON_KP_SUBTRACT = 333,
	ABYSS_BUTTON_KP_ADD = 334,
	ABYSS_BUTTON_KP_ENTER = 335,
	ABYSS_BUTTON_KP_EQUAL = 336,
	ABYSS_BUTTON_LEFT_SHIFT = 340,
	ABYSS_BUTTON_LEFT_CONTROL = 341,
	ABYSS_BUTTON_LEFT_ALT = 342,
	ABYSS_BUTTON_LEFT_SUPER = 343,
	ABYSS_BUTTON_RIGHT_SHIFT = 344,
	ABYSS_BUTTON_RIGHT_CONTROL = 345,
	ABYSS_BUTTON_RIGHT_ALT = 346,
	ABYSS_BUTTON_RIGHT_SUPER = 347,
	ABYSS_BUTTON_MENU = 348
};

#endif