#ifndef ENUMS_H
#define ENUMS_H

enum class ABYSS_FILE_TYPE
{
	ABYSS_TEXT_FILE = 1,
	ABYSS_BINARY_FILE
};

enum class ABYSS_ENDIAN_TYPE
{
	ABYSS_ENDIAN_UNKNOWN = 0,
	ABYSS_ENDIAN_LITTLE,
	ABYSS_ENDIAN_BIG,
	ABYSS_ENDIAN_MIDDLE
};

enum class ABYSS_COORDINATE_TYPE
{
	ABYSS_LEFT_HANDED = 1,
	ABYSS_RIGHT_HANDED
};

enum class ABYSS_PLANE_STATUS
{
	ABYSS_PLANE_FRONT = 1,
	ABYSS_PLANE_BACK,
	ABYSS_PLANE_ON_PLANE,
	ABYSS_PLANE_CLIPPED,
	ABYSS_PLANE_CULLED,
	ABYSS_PLANE_VISIBLE
};

// General defines, etc.
enum class ABYSS_RESULT
{
	ABYSS_FAIL = 0,
	ABYSS_SUCCESS,
	ABYSS_VERTEX_SHADER_FAIL,
	ABYSS_PIXEL_SHADER_FAIL,
	ABYSS_SHADER_FAIL,
	ABYSS_PARAMETERS_FAIL,
	ABYSS_DEVICE_FAIL
};

// Networking defines, etc.
enum class ABYSS_NETWORK_MESSAGE_TYPE
{
	ABYSS_MESSAGE_SERVER_DISCONNECT = 0,
	ABYSS_MESSAGE_CLIENT_DISCONNECT,
	ABYSS_MESSAGE_FORCE_DISCONNECT,
	ABYSS_MESSAGE_CONNECT_ACCEPTED,
	ABYSS_MESSAGE_SEND_ERROR,
	ABYSS_MESSAGE_RESPOND_REQUIRE,
	ABYSS_MESSAGE_RESPOND_OK
};

enum class ABYSS_NETWORK_TYPE
{
	ABYSS_NETWORK_NULL = 0,
	ABYSS_NETWORK_SERVER,
	ABYSS_NETWORK_CLIENT
};

enum class ABYSSNETWORKRESULT
{
	ABYSS_NO_DATA = 0,
	ABYSS_DATA_FAIL,
	ABYSS_PARTIAL_DATA,
	ABYSS_DATA_SUCCESS
};

// Defines, enums, etc dealing with RENDERING.
enum class ABYSS_RENDER_STATE
{
	ABYSS_DEPTH_TESTING = 1,
	ABYSS_SMOOTH_SHADING,
	ABYSS_TEXTURE_2D,
	ABYSS_TEXTURE_CUBE,
	ABYSS_ALPHA_TESTING,
	ABYSS_BACK_CCW_CULLING,
	ABYSS_BACK_CW_CULLING,
	ABYSS_FRONT_CCW_CULLING,
	ABYSS_FRONT_CW_CULLING,
	ABYSS_TOTAL_RENDER_STATES
};

enum class ABYSS_ALPHA_STATE
{
	ABYSS_ALPHA_LESS = 1,
	ABYSS_ALPHA_GREATER
};

enum class ABYSS_FILTER_TYPE
{
	ABYSS_NO_FILTER = 0,
	ABYSS_MIN_POINT_FILTER,
	ABYSS_MAG_POINT_FILTER,
	ABYSS_MIP_POINT_FILTER,
	ABYSS_MIN_LINEAR_FILTER,
	ABYSS_MAG_LINEAR_FILTER,
	ABYSS_MIP_LINEAR_FILTER,
	ABYSS_USE_ANSIO_FILTER,
	ABYSS_S_REPEAT_FILTER,
	ABYSS_T_REPEAT_FILTER,
	ABYSS_R_REPEAT_FILTER,
	ABYSS_S_CLAMP_FILTER,
	ABYSS_T_CLAMP_FILTER,
	ABYSS_R_CLAMP_FILTER,
	ABYSS_S_EDGE_CLAMP_FILTER,
	ABYSS_T_EDGE_CLAMP_FILTER,
	ABYSS_R_EDGE_CLAMP_FILTER
};

enum class ABYSS_TEXTURE_TYPE
{
	ABYSS_TEX2D_TYPE = 1,
	ABYSS_CUBE_TYPE
};

enum class ABYSS_TEXTURE_FORMAT
{
	ABYSS_TEX_UNSIGNED_BYTE = 1,
	ABYSS_TEX_FLOAT
};

enum class ABYSS_MATRIX_TYPE
{
	ABYSS_PROJECTION_MATRIX = 1,
	ABYSS_MODELVIEW_MATRIX,
	ABYSS_TEXTURE_MATRIX,
	ABYSS_MVP_MATRIX
};

enum class ABYSS_MATRIX_FORMAT
{
	ABYSS_IDENTITY_MATRIX = 1,
	ABYSS_TRANSPOSE_MATRIX,
	ABYSS_INVERSE_MATRIX,
	ABYSS_INVERSE_TRANSPOSE_MATRIX
};

enum class ABYSS_PROJECTION_TYPE
{
	ABYSS_PROJECTION_NULL = 0,
	ABYSS_PERSPECTIVE_TYPE,
	ABYSS_ORTHO_TYPE
};

enum class ABYSS_ELEMENT_TYPE
{
	ABYSS_ELEMENT_TYPE_NULL = 0,
	ABYSS_ELEMENT_TYPE_IGNORE_2F,
	ABYSS_ELEMENT_TYPE_IGNORE_3F,
	ABYSS_ELEMENT_TYPE_VERTEX_3F,
	ABYSS_ELEMENT_TYPE_NORMAL_3F,
	ABYSS_ELEMENT_TYPE_COLOR_3F,
	ABYSS_ELEMENT_TYPE_TEX1_2F,
	ABYSS_ELEMENT_TYPE_TEX2_2F,
	ABYSS_ELEMENT_TYPE_TEX3_2F,
	ABYSS_ELEMENT_TYPE_TEX4_2F,
	ABYSS_ELEMENT_TYPE_TEX5_2F,
	ABYSS_ELEMENT_TYPE_TEX6_2F,
	ABYSS_ELEMENT_TYPE_TEX7_2F,
	ABYSS_ELEMENT_TYPE_TEX8_2F,
	ABYSS_ELEMENT_TYPE_TEX1_3F,
	ABYSS_ELEMENT_TYPE_TEX2_3F,
	ABYSS_ELEMENT_TYPE_TEX3_3F,
	ABYSS_ELEMENT_TYPE_TEX4_3F,
	ABYSS_ELEMENT_TYPE_TEX5_3F,
	ABYSS_ELEMENT_TYPE_TEX6_3F,
	ABYSS_ELEMENT_TYPE_TEX7_3F,
	ABYSS_ELEMENT_TYPE_TEX8_3F
};

enum class ABYSS_PRIMITIVE_TYPE
{
	ABYSS_PRIMITIVE_NULL = 0,
	ABYSS_PRIMITIVE_POINT_LIST,
	ABYSS_PRIMITIVE_TRI_LIST,
	ABYSS_PRIMITIVE_TRI_STRIP,
	ABYSS_PRIMITIVE_LINE_LIST,
	ABYSS_PRIMITIVE_LINE_STRIP
};

enum class ABYSS_SHADER_TYPE
{
	ABYSS_VERTEX_SHADER = 1,
	ABYSS_PIXEL_SHADER
};

enum class ABYSS_OCTREE_NODE_ID
{
	TOP_FRONT_LEFT = 0,
	TOP_FRONT_RIGHT,
	TOP_BACK_LEFT,
	TOP_BACK_RIGHT,
	BOTTOM_FRONT_LEFT,
	BOTTOM_FRONT_RIGHT,
	BOTTOM_BACK_LEFT,
	BOTTOM_BACK_RIGHT
};

#endif